build site:
  image: node:6
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:6
  stage: test
  script:
    - npm install --progress=false
    - npm run test

e2e test:
  image: ubuntu:16.04
  stage: test
  script:
    - apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates \
      apt-transport-https \
      openjdk-8-jre-headless \
      curl \
      xz-utils \
      unzip \
      bzip2 \
      wget \
      npm \
      && rm -rf /var/lib/apt/lists/*
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
      && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
      && apt-get update -qqy \
      && apt-get -qqy install google-chrome-unstable \
      && rm /etc/apt/sources.list.d/google-chrome.list \
      && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
    - npm install --progress=false
    - npm run e2e
  
deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - scp -prv -P10428 dist/* myseriesc@davidsouza.tech:~/public_html/blog/