build site:
  image: node:6
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:6
  stage: test
  script:
    - npm install --progress=false
    - npm run test

e2e test:
  image: ubuntu:16.04
  stage: test
  script:
    - apt-get update
    - apt-get -y install curl
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install -y nodejs openjdk-8-jre libgconf-2-4
    - npm install --progress=false
    - npm run e2e
deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - scp -prv -P10428 dist/* myseriesc@davidsouza.tech:~/public_html/blog/